### ISSUE TITLE
About the problem you meet

### ISSUE THREAD

**Issue by Mike66666** [Lukelluke/MCD-toolkit-polished-useful#1]
I modify the code as your examples,but I still meet the shape mismatch problem

**Comment by Lukelluke** [comment]
Hello, sorry for late response.

The same question had been asked by many guys. U need to notice that "Whether the ***htk_io/vecseq.py*** file is the corresponding file that u wanna to modify"!

That is to say, there are several different files named  vecseq.py, and u need to find out which is the right one that u r using during calculating the MCD.

Do let me know if u have any further question.

Best wishes,

Luke Huang
